### ISSUE TITLE
Graph modelling

### ISSUE THREAD

**Issue by maximepvrt** [outworkers/reactiveneo#12]
In your example, what is your Index class ? it does not exist in your package.
In PersonNode, for me my idea thinks that StringAttribute want have parameters, same with IntegerAttribute and in Person(name[String](data), age[Int](data)), it's failed between hooks.

sorry, I am beginner in scala and neo4j

**Comment by maximepvrt** [comment]
It's possible to connect in our graph with auth ?

**Comment by alexflav23** [comment]
@bjankie1 Perhaps you could help @maximepvrt, I don't know how to answer this so I'm assuming it's a change you've done recently.

**Comment by maximepvrt** [comment]
no news :cry: I am using this module for my startup project :)

**Comment by bjankie1** [comment]
Hi,
I have limited access to internet. I will return to your question this
evening.

Best,
Bartosz

**Comment by bjankie1** [comment]
In the example PersonNode serves the purpose of schema definition while Person is the case class serving the purpose of data transfer object. Indexes creation has not been wrapped with API yet, but it's a planned extension. 
Please have a look at a test that is a showcase for building cypher constructs using reactiveneo DSL:
com.websudos.reactiveneo.dsl.MatchQueryTest

**Comment by maximepvrt** [comment]
thanks. And for save, update or delate a node, how we do?

**Comment by bjankie1** [comment]
There is no DSL support for these operations yet, but it's planned. It
doesn't need that you cannot do that using Cypher using REST client
directly. Please refer to com.websudos.reactiveneo.client.RestClientSpec
for details.

**Comment by maximepvrt** [comment]
OK :/ Think you add this quickly ? I'm not good enough in scala to start this implementation.I will like to keep using your library :smile:

**Comment by bjankie1** [comment]
I think that extending DSL query API is higher on the priority list but I will give it a thought. For now please try to use this code:

``` scala
val service = RestConnection("localhost", 7474)
val query = "CREATE (n) RETURN id(n)"
implicit val parsRester: Reads[InsertResult] = __.read[Int].map { arr =>
  InsertResult(arr)
}
val result = service.makeRequest[InsertResult](query).execute
```

where the InsertResult is a simple case class that you can add to your code:

``` scala
case class InsertResult(id: Int)
```

**Comment by maximepvrt** [comment]
it created empty node without type.

**Comment by bjankie1** [comment]
Yes, this is what it does. To create node with a label you can use another Cypher:

```
CREATE (n:Person) RETURN id(n)
```

or with some attributes:

```
CREATE (n:Person { name : 'Andres', title : 'Developer' }) RETURN id(n)
```
