### ISSUE TITLE
File name ~>.scala prevents checkout on windows.

### ISSUE THREAD

**Issue by zarthross** [outworkers/reactiveneo#17]
I'm using MS Windows 8.1 with NTFS filesystem and the file reactiveneo/reactiveneo-dsl/src/test/scala/~>.scala prevents checkout since ~>.scala is not a valid file name.  Please change the file name to something non symbolic.

**Comment by bjankie1** [comment]
Sure, I will apply a patch right away.

**Comment by alexflav23** [comment]
Hi @zarthross,

0.3.1 should be live on Maven Central within the next few hours to address this issue. Hope that helps, many thanks for your bug report and please let us know if there are any other issues moving forward!

Regards,
Flavian
