### ISSUE TITLE
(Not an issue) Project still active?

### ISSUE THREAD

**Issue by willks** [outworkers/reactiveneo#21]
Hi,
  I was looking to use this project for my next graph implementation. Is this project still being supported or has reached a level of maturity where ongoing fixes aren't required? 

Thanks

**Comment by alexflav23** [comment]
Hi @willks,

We are still working on this project, although not as actively as on our other DSLs. We do hope to ramp up our efforts on an ever increasing basis, so if you find any bugs or need any new features, we will do our best to help. My best guess is that the project is in semi mature stage, it works very well but supports a limited subset of Cipher features.

Regards,
Flavian

**Comment by willks** [comment]
Thanks for the update! Gives me more confidence to adopt this now. I'm already using your excellent PhantomDSL, no issues to date with that.

Cheers
