### ISSUE TITLE
Can you add your module to a repository for sbt ?

### ISSUE THREAD

**Issue by maximepvrt** [outworkers/reactiveneo#9]

**Comment by alexflav23** [comment]
@maximepvrt We will publish to Maven Central very shortly, starting with today even. I will let you know as soon as it's live.

**Comment by maximepvrt** [comment]
Thanks, but your module is empty when it's downloaded from maven :smile:

**Comment by alexflav23** [comment]
@maximepvrt That sounds fairly weird. If you explicitly depend on the dsl and testing modules you should be fine.

**Comment by maximepvrt** [comment]
After unzipped your http://search.maven.org/remotecontent?filepath=com/websudos/reactiveneo_2.10/0.3.0/reactiveneo_2.10-0.3.0.jar, there is just the MANIFEST.MF file

**Comment by alexflav23** [comment]
You should depend only on the submodules:

``` scala
libraryDependencies ++= Seq(
  "com.websudos" %% "reactiveneo-dsl" % "0.3.0",
  "com.websudos" %% "reactiveneo-testing" % "0.3.0",
)

```

**Comment by maximepvrt** [comment]
thanks you so much !
